#!/bin/bash
set -eo pipefail

plugin_root="${BASH_SOURCE%/*}/.."

# Try to use explicit python3 if its installed
python_bin="python3"
if ! [[ -x "$(command -v ${python_bin})" ]]; then
  python_bin="python"
fi

${python_bin}  "${plugin_root}/python/checkout.py"
